name: Continuous Integration

on:
    pull_request

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Node.js
              uses: actions/setup-node@v3  # Atualizando para a versão 3
              with:
                node-version: '22'  # Certifique-se de que esta versão do Node.js seja a que você precisa
                
            - name: Install, build and test
              run: |
                npm install
                npm run build
                npm run test
