name: Continuous Integration

on:
    pull_request

jobs:
    continuous-integration:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '22'
                
            - name: Install, build and test
              run: |
                npm install
                npm run build
                npm run test

            - name: Deploy to VPS
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                USER: ${{ secrets.VPS_USER }} 
                HOST: ${{ secrets.VPS_HOST }} 
                DEST: ${{ secrets.VPS_DEST }} 
              run: |
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                
                ssh-keyscan -p 2266 $HOST >> ~/.ssh/known_hosts
                rsync -avz -e "ssh -p 2266" --delete ./dist/ $USER@$HOST:$DEST
            
            - name: Test SSH Connection
              run: |
                echo "USER: $USER"
                echo "HOST: $HOST"
                echo "DEST: $DEST" 